package edu.ucne.skyplanerent.presentation.aeronave

import android.net.Uri
import edu.ucne.skyplanerent.data.remote.dto.AeronaveDTO

data class AeronaveUiState(
    val aeronaveId: Int? = null,
    val estadoId: Int? = 0,
    val modeloAvion: String = "",
    val descripcionCategoria: String = "",
    val registracion: String = "",
    val costoXHora: Double? = 0.0,
    val descripcionAeronave: String = "",
    val velocidadMaxima: Double? = 0.0,
    val descripcionMotor: String = "",
    val capacidadCombustible: Int = 0,
    val consumoXHora: Int = 0,
    val peso: Double? = 0.0,
    val rango: Int = 0,
    val capacidadPasajeros: Int = 0,
    val altitudMaxima: Int = 0,
    val licencia: String = "",
    val imageUri: Uri? = null,
    val imageUrl: String? = null,
    val errorEstadoId: String? = null,
    val errorModeloAvion: String? = null,
    val errorDescripcionCategoria: String? = null,
    val errorRegistracion: String? = null,
    val errorCostoXHora: String? = null,
    val errorDescripcionAeronave: String? = null,
    val errorVelocidadMaxima: String? = null,
    val errorDescripcionMotor: String? = null,
    val errorCapacidadCombustible: String? = null,
    val errorConsumoXHora: String? = null,
    val errorPeso: String? = null,
    val errorRango: String? = null,
    val errorCapacidadPasajeros: String? = null,
    val errorAltitudMaxima: String? = null,
    val errorLicencia: String? = null,
    val errorMessage: String? = null,
    val isSuccess: Boolean = false,
    val successMessage: String? = null,
    val isLoading: Boolean = false,
    val aeronaves: List<AeronaveDTO> = emptyList(),
    val categoriaId: Int? = null
)